# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"frequencer": "00_frequencer.ipynb"}

modules = ["frequencer.py"]

doc_url = "https://fregat17.github.io/frequencer/"

git_url = "https://github.com/fregat17/frequencer/tree/master/"

def custom_doc_links(name): return None
